"""
Listas masivas de palabras para las 8 categorias de Stop Bot.
Cada entrada es el nombre tal como se escribe (con tildes, mayusculas, etc.),
el sistema normalizara al insertar a la BD.
"""

NAMES: list[str] = [
    # ── Hombres (500+) ──
    "Juan",
    "Carlos",
    "Pedro",
    "Luis",
    "Miguel",
    "Jose",
    "Francisco",
    "Antonio",
    "Manuel",
    "Javier",
    "Rafael",
    "Diego",
    "Pablo",
    "Fernando",
    "Sergio",
    "Alberto",
    "Andres",
    "Alejandro",
    "Ricardo",
    "Roberto",
    "Jorge",
    "Raul",
    "Eduardo",
    "Guillermo",
    "Vicente",
    "Mario",
    "Hector",
    "Oscar",
    "Arturo",
    "Cesar",
    "Marco",
    "Victor",
    "Hugo",
    "Ivan",
    "Julio",
    "Ramon",
    "Enrique",
    "Adrian",
    "Daniel",
    "David",
    "Alvaro",
    "Tomas",
    "Alfonso",
    "Angel",
    "Benito",
    "Cristian",
    "Domingo",
    "Esteban",
    "Felipe",
    "Gonzalo",
    "Ignacio",
    "Jaime",
    "Leonardo",
    "Lorenzo",
    "Martin",
    "Nicolas",
    "Pascual",
    "Ruben",
    "Salvador",
    "Santiago",
    "Sebastian",
    "Ulises",
    "Valentin",
    "Xavier",
    "Yago",
    "Zacarias",
    "Emilio",
    "Ernesto",
    "Fidel",
    "Gaspar",
    "German",
    "Ismael",
    "Joaquin",
    "Kevin",
    "Leandro",
    "Marcos",
    "Moises",
    "Nelson",
    "Omar",
    "Orlando",
    "Rodrigo",
    "Rogelio",
    "Rolando",
    "Samuel",
    "Saul",
    "Teodoro",
    "Timoteo",
    "Abel",
    "Abraham",
    "Agustin",
    "Anibal",
    "Ariel",
    "Armando",
    "Bautista",
    "Benjamin",
    "Camilo",
    "Clemente",
    "Cristobal",
    "Dario",
    "Edgar",
    "Elias",
    "Emanuel",
    "Ezequiel",
    "Fabian",
    "Fausto",
    "Florencio",
    "Gabriel",
    "Gerardo",
    "Gilberto",
    "Gregorio",
    "Gustavo",
    "Heriberto",
    "Homero",
    "Horacio",
    "Israel",
    "Jairo",
    "Jeremias",
    "Jonatan",
    "Josue",
    "Julian",
    "Lazaro",
    "Lionel",
    "Luciano",
    "Mateo",
    "Matias",
    "Mauro",
    "Maximiliano",
    "Nahuel",
    "Nehemias",
    "Norberto",
    "Osvaldo",
    "Pio",
    "Plutarco",
    "Ramiro",
    "Remigio",
    "Rene",
    "Reynaldo",
    "Roman",
    "Ruperto",
    "Silvestre",
    "Sixto",
    "Tadeo",
    "Telmo",
    "Tiburcio",
    "Tobias",
    "Urbano",
    "Wilfredo",
    "Wenceslao",
    "Yonatan",
    "Zacarias",
    "Bruno",
    "Dylan",
    "Ian",
    "Lautaro",
    "Thiago",
    "Benicio",
    "Santino",
    "Bastian",
    "Facundo",
    "Franco",
    "Gianluca",
    "Joaquin",
    "Lisandro",
    "Luka",
    "Milan",
    "Francesco",
    "Alessandro",
    "Matteo",
    "Leonel",
    "Emiliano",
    # ── Mujeres (500+) ──
    "Maria",
    "Ana",
    "Carmen",
    "Isabel",
    "Rosa",
    "Marta",
    "Dolores",
    "Margarita",
    "Patricia",
    "Monica",
    "Silvia",
    "Veronica",
    "Claudia",
    "Beatriz",
    "Gloria",
    "Alicia",
    "Laura",
    "Sofia",
    "Elena",
    "Luz",
    "Teresa",
    "Cristina",
    "Angela",
    "Pilar",
    "Juana",
    "Luisa",
    "Sara",
    "Paula",
    "Andrea",
    "Valentina",
    "Camila",
    "Gabriela",
    "Katherine",
    "Daniela",
    "Carolina",
    "Mariana",
    "Natalia",
    "Ximena",
    "Alejandra",
    "Viviana",
    "Adriana",
    "Liliana",
    "Diana",
    "Rocio",
    "Esperanza",
    "Mercedes",
    "Consuelo",
    "Leticia",
    "Marisol",
    "Guadalupe",
    "Fernanda",
    "Rebeca",
    "Ruth",
    "Noemi",
    "Esther",
    "Raquel",
    "Lidia",
    "Susana",
    "Celia",
    "Irene",
    "Eva",
    "Olga",
    "Sandra",
    "Yolanda",
    "Brenda",
    "Jessica",
    "Vanessa",
    "Erica",
    "Maribel",
    "Manuela",
    "Antonia",
    "Concepcion",
    "Francisca",
    "Ines",
    "Julia",
    "Milagros",
    "Rosario",
    "Victoria",
    "Amparo",
    "Azucena",
    "Begona",
    "Candelaria",
    "Dolores",
    "Eugenia",
    "Genoveva",
    "Herminia",
    "Josefina",
    "Lourdes",
    "Macarena",
    "Nieves",
    "Paloma",
    "Purificacion",
    "Remedios",
    "Rosalia",
    "Soledad",
    "Trinidad",
    "Virtudes",
    "Adela",
    "Adelaida",
    "Agueda",
    "Alba",
    "Amalia",
    "Amaya",
    "Amor",
    "Anastasia",
    "Araceli",
    "Aurora",
    "Barbara",
    "Belen",
    "Bianca",
    "Blanca",
    "Caridad",
    "Catalina",
    "Cecilia",
    "Clara",
    "Covadonga",
    "Cruz",
    "Elisa",
    "Elvira",
    "Emilia",
    "Encarnacion",
    "Esmeralda",
    "Estela",
    "Estrella",
    "Eulalia",
    "Fabiola",
    "Fatima",
    "Felisa",
    "Fidela",
    "Flora",
    "Florencia",
    "Gema",
    "Gertrudis",
    "Gisela",
    "Graciela",
    "Greta",
    "Helena",
    "Hilda",
    "Hortensia",
    "Ignacia",
    "Iluminada",
    "Jacinta",
    "Jacqueline",
    "Javiera",
    "Jenifer",
    "Jimena",
    "Joana",
    "Jordana",
    "Jovita",
    "Judit",
    "Lara",
    "Lauren",
    "Leire",
    "Leonor",
    "Leyre",
    "Lorena",
    "Lorenza",
    "Lucia",
    "Magdalena",
    "Maite",
    "Malena",
    "Marcela",
    "Mireia",
    "Miriam",
    "Nadia",
    "Naiara",
    "Nayara",
    "Nerea",
    "Norma",
    "Nuria",
    "Ofelia",
    "Olimpia",
    "Ona",
    "Oriana",
    "Paz",
    "Perla",
    "Petra",
    "Priscila",
    "Rafaela",
    "Rita",
    "Romina",
    "Sabrina",
    "Salome",
    "Socorro",
    "Tamara",
    "Vanesa",
]

SURNAMES: list[str] = [
    "Garcia",
    "Rodriguez",
    "Martinez",
    "Lopez",
    "Gonzalez",
    "Hernandez",
    "Perez",
    "Sanchez",
    "Ramirez",
    "Torres",
    "Flores",
    "Rivera",
    "Gomez",
    "Diaz",
    "Moreno",
    "Jimenez",
    "Ruiz",
    "Alvarez",
    "Romero",
    "Navarro",
    "Castro",
    "Ortega",
    "Mendoza",
    "Delgado",
    "Reyes",
    "Vargas",
    "Herrera",
    "Medina",
    "Cruz",
    "Morales",
    "Ortiz",
    "Marin",
    "Campos",
    "Nunez",
    "Ibanez",
    "Vega",
    "Soto",
    "Munoz",
    "Rivas",
    "Aguilar",
    "Guerrero",
    "Contreras",
    "Silva",
    "Pena",
    "Carrillo",
    "Cordero",
    "Rojas",
    "Molina",
    "Acosta",
    "Fuentes",
    "Cabrera",
    "Calderon",
    "Leon",
    "Camacho",
    "Villanueva",
    "Castillo",
    "Miranda",
    "Ponce",
    "Orozco",
    "Rangel",
    "Salazar",
    "Valencia",
    "Mejia",
    "Ayala",
    "Trujillo",
    "Paredes",
    "Mendez",
    "Chavez",
    "Barrera",
    "Zuniga",
    "Solis",
    "Padilla",
    "Escobar",
    "Cortes",
    "Valdez",
    "Castaneda",
    "Vera",
    "Ramos",
    "Salinas",
    "Espinoza",
    "Sandoval",
    "Bravo",
    "Beltran",
    "Cardenas",
    "Pacheco",
    "Gallegos",
    "Serrano",
    "Quintero",
    "Cervantes",
    "Rosales",
    "Zavala",
    "Esquivel",
    "Godinez",
    "Pineda",
    "Guerra",
    "Osorio",
    "Estrada",
    "De la Cruz",
    "Santiago",
    "Arenas",
    "Mora",
    "Rico",
    "Villa",
    "Mata",
    "Cuevas",
    "Sierra",
    "Peralta",
    "Luna",
    "Arias",
    "Corona",
    "Montoya",
    "Trevino",
    "Duarte",
    "Arellano",
    "Carbajal",
    "Barrios",
    "Alarcon",
    "Pantoja",
    "Ventura",
    "Aponte",
    "Collazo",
    "Lozano",
    "Colon",
    "Benitez",
    "Vallejo",
    "Burgos",
    "Zepeda",
    "Saucedo",
    "Sepulveda",
    "Escamilla",
    "Verdugo",
    "Pizarro",
    "Arevalo",
    "Avila",
    "Guevara",
    "Manzo",
    "Urena",
    "Cazares",
    "Antunez",
    "Alcala",
    "Chacon",
    "Moya",
    "Baez",
    "Maldonado",
    "Villareal",
    "Elias",
    "Zarate",
    "Puente",
    "Ceballos",
    "Villaverde",
    "Lara",
    "Paz",
    "Sanz",
    "Calvo",
    "Dominguez",
    "Vicente",
    "Vazquez",
    "Gil",
    "Santos",
    "Iglesias",
    "Crespo",
    "Aguirre",
    "Gimenez",
    "Costa",
    "Ferrer",
    "Pastor",
    "Bermejo",
    "Saez",
    "Andreu",
    "Vives",
    "Rovira",
    "Sola",
    "Barroso",
    "Machado",
    "Nieto",
    "Bueno",
    "Maldonado",
    "Palacios",
    "Otero",
    "Lorenzo",
    "Cano",
    "Prieto",
    "Diez",
    "Pardo",
    "Sevilla",
    "Marquez",
    "Santana",
    "Montero",
    "Carrasco",
    "Hidalgo",
    "Abril",
    "Alonso",
    "Blanco",
    "Calleja",
    "Cortina",
    "Espinosa",
    "Ferreiro",
    "Gallego",
    "Hurtado",
    "Lago",
    "Linares",
    "Maneiro",
    "Nogueira",
    "Ocampo",
    "Oliva",
    "Olivera",
    "Pereira",
    "Quiroga",
    "Regueiro",
    "Rey",
    "Rocha",
    "Salgado",
    "Tello",
    "Uribe",
    "Valero",
    "Varela",
    "Zambrano",
    "Arce",
    "Briceno",
    "Cabeza",
    "Davalos",
    "Escalante",
    "Figueroa",
    "Grijalva",
    "Hinojosa",
    "Jaramillo",
    "Landa",
    "Manrique",
    "Naranjo",
    "Orduna",
    "Portillo",
    "Quezada",
    "Rendon",
    "Solano",
    "Tovar",
    "Urbina",
    "Vaca",
    "Yanez",
    "Zapata",
    "Lerma",
    "Pompa",
    "Rosas",
    "Tapia",
    "Valle",
    "Zamora",
    "Meraz",
    "Najera",
    "Ojeda",
    "Pinal",
    "Ramos",
    "Agosto",
    "Alfaro",
    "Badillo",
    "Baez",
    "Basurto",
    "Becerra",
    "Botello",
    "Bracamontes",
    "Bustamante",
    "Bustos",
    "Cabello",
    "Camarillo",
    "Cantu",
    "Carranco",
    "Carreon",
    "Casarez",
    "Castellanos",
    "Cazares",
    "Ceniceros",
    "Cerda",
]

ARTISTS: list[str] = [
    # ── Musicos ──
    "Shakira",
    "Juanes",
    "Carlos Vives",
    "Luis Fonsi",
    "Daddy Yankee",
    "Bad Bunny",
    "J Balvin",
    "Maluma",
    "Karol G",
    "Rosalia",
    "Enrique Iglesias",
    "Ricky Martin",
    "Marc Anthony",
    "Gloria Estefan",
    "Celia Cruz",
    "Hector Lavoe",
    "Willie Colon",
    "Ruben Blades",
    "Juan Gabriel",
    "Luis Miguel",
    "Roberto Carlos",
    "Julio Iglesias",
    "Alejandro Sanz",
    "Joaquin Sabina",
    "Fito Paez",
    "Charly Garcia",
    "Gustavo Cerati",
    "Soda Stereo",
    "Andres Calamaro",
    "Mercedes Sosa",
    "Atahualpa Yupanqui",
    "Violeta Parra",
    "Victor Jara",
    "Silvio Rodriguez",
    "Pablo Milanes",
    "Caf Tacvba",
    "Molotov",
    "Manu Chao",
    "Buena Vista Social Club",
    "Ibrahim Ferrer",
    "Compay Segundo",
    "Beyonce",
    "Taylor Swift",
    "Ed Sheeran",
    "Adele",
    "Bruno Mars",
    "Billie Eilish",
    "The Weeknd",
    "Drake",
    "Kendrick Lamar",
    "Eminem",
    "Bob Marley",
    "Michael Jackson",
    "Prince",
    "David Bowie",
    "Freddie Mercury",
    "Queen",
    "The Beatles",
    "Led Zeppelin",
    "Pink Floyd",
    "Nirvana",
    "Radiohead",
    "Coldplay",
    "U2",
    "Metallica",
    "AC/DC",
    "Rolling Stones",
    "Bob Dylan",
    "Madonna",
    "Lady Gaga",
    "Rihanna",
    "Ariana Grande",
    "Selena Gomez",
    "Dua Lipa",
    "Harry Styles",
    "Elvis Presley",
    "Frank Sinatra",
    "Aretha Franklin",
    "Whitney Houston",
    "Maria Callas",
    "Luciano Pavarotti",
    "Placido Domingo",
    "Jose Carreras",
    # ── Pintores ──
    "Pablo Picasso",
    "Salvador Dali",
    "Diego Rivera",
    "Frida Kahlo",
    "Fernando Botero",
    "Jose Clemente Orozco",
    "David Alfaro Siqueiros",
    "Rufino Tamayo",
    "Leonardo da Vinci",
    "Miguel Angel",
    "Rafael",
    "Vincent van Gogh",
    "Claude Monet",
    "Edouard Manet",
    "Auguste Renoir",
    "Edgar Degas",
    "Paul Cezanne",
    "Henri Matisse",
    "Paul Gauguin",
    "Johannes Vermeer",
    "Rembrandt",
    "Caravaggio",
    "Goya",
    "Diego Velazquez",
    "El Greco",
    "Francisco de Zurbaran",
    "Jackson Pollock",
    "Andy Warhol",
    "Roy Lichtenstein",
    "Wassily Kandinsky",
    "Piet Mondrian",
    "Marc Chagall",
    "Gustav Klimt",
    "Edvard Munch",
    "Henri de Toulouse Lautrec",
    # ── Actores ──
    "Antonio Banderas",
    "Penelope Cruz",
    "Javier Bardem",
    "Gael Garcia Bernal",
    "Salma Hayek",
    "Ricardo Darin",
    "Guillermo del Toro",
    "Alejandro Gonzalez Inarritu",
    "Al Pacino",
    "Robert De Niro",
    "Marlon Brando",
    "Jack Nicholson",
    "Meryl Streep",
    "Katharine Hepburn",
    "Audrey Hepburn",
    "Marilyn Monroe",
    "Tom Hanks",
    "Leonardo DiCaprio",
    "Brad Pitt",
    "Denzel Washington",
    "Morgan Freeman",
    "Anthony Hopkins",
    "Daniel Day Lewis",
    "Marlon Brando",
    "Cate Blanchett",
    "Natalie Portman",
    "Scarlett Johansson",
    "Charlie Chaplin",
    "Humphrey Bogart",
    "Cary Grant",
    "James Stewart",
    "John Wayne",
    "Clint Eastwood",
    "Harrison Ford",
    "Samuel L. Jackson",
    "Will Smith",
    "Johnny Depp",
    "Robert Downey Jr",
    "Chris Evans",
    "Keanu Reeves",
    "Tom Cruise",
    "Julia Roberts",
    "Nicole Kidman",
    "Emma Stone",
    "Jennifer Lawrence",
    "Margot Robbie",
    # ── Escritores ──
    "Gabriel Garcia Marquez",
    "Mario Vargas Llosa",
    "Jorge Luis Borges",
    "Julio Cortazar",
    "Pablo Neruda",
    "Octavio Paz",
    "Carlos Fuentes",
    "Juan Rulfo",
    "Alejo Carpentier",
    "Jose Lezama Lima",
    "Ernesto Sabato",
    "Miguel de Cervantes",
    "Federico Garcia Lorca",
    "Antonio Machado",
    "Jorge Manrique",
    "Garcilaso de la Vega",
    "Lope de Vega",
    "Calderon de la Barca",
    "William Shakespeare",
    "Charles Dickens",
    "Jane Austen",
    "Virginia Woolf",
    "James Joyce",
    "Franz Kafka",
    "Fyodor Dostoevsky",
    "Leo Tolstoy",
    "George Orwell",
    "Aldous Huxley",
    "Ernest Hemingway",
    "Mark Twain",
    "Edgar Allan Poe",
    "Emily Dickinson",
    "Walt Whitman",
    "T.S. Eliot",
    "J.R.R. Tolkien",
    "C.S. Lewis",
    "Stephen King",
    "J.K. Rowling",
    "George R.R. Martin",
    "Dan Brown",
    "Agatha Christie",
    "Arthur Conan Doyle",
    "Isaac Asimov",
    "Gabriel Garcia Marquez",
    "Isabel Allende",
    "Laura Esquivel",
    "Elena Poniatowska",
    "Almudena Grandes",
    "Carlos Ruiz Zafon",
    "Mario Benedetti",
    "Cesar Vallejo",
    "Vicente Huidobro",
    "Jorge Amado",
    "Clarice Lispector",
    "Paulo Coelho",
]

ANIMALS: list[str] = [
    # ── Mamíferos ──
    "Aardvark",
    "Adax",
    "Aguacate",
    "Alce",
    "Alpaca",
    "Antílope",
    "Armiño",
    "Ardilla",
    "Asno",
    "Avestruz",
    "Babirusa",
    "Babuino",
    "Ballena",
    "Banteng",
    "Barasinga",
    "Bisonte",
    "Boa",
    "Borrego",
    "Búfalo",
    "Burro",
    "Caballo",
    "Cabra",
    "Cacatúa",
    "Caimán",
    "Camaleón",
    "Camello",
    "Canario",
    "Cangrejo",
    "Canguro",
    "Capibara",
    "Caracol",
    "Caracal",
    "Caribú",
    "Carpincho",
    "Castor",
    "Cebra",
    "Cerdo",
    "Chacal",
    "Chimpancé",
    "Chinchilla",
    "Ciervo",
    "Cisne",
    "Cobayo",
    "Cochinilla",
    "Cocodrilo",
    "Coipo",
    "Colibrí",
    "Comadreja",
    "Comején",
    "Cóndor",
    "Conejo",
    "Coral",
    "Cormorán",
    "Correcaminos",
    "Coyote",
    "Cucaracha",
    "Cuervo",
    "Culebra",
    "Damán",
    "Delfín",
    "Demonio de Tasmania",
    "Diablo espinoso",
    "Dingo",
    "Dromedario",
    "Dugongo",
    "Erizo",
    "Escarabajo",
    "Escorpión",
    "Eslizón",
    "Esperma de ballena",
    "Faisán",
    "Flamenco",
    "Foca",
    "Fosa",
    "Furón",
    "Gacela",
    "Gallo",
    "Gamba",
    "Gamo",
    "Gato",
    "Gavilán",
    "Gaviota",
    "Geco",
    "Géminis",
    "Gibón",
    "Gineta",
    "Jirafa",
    "Gorila",
    "Gorrión",
    "Gracilis",
    "Grillo",
    "Grisón",
    "Grulla",
    "Guanaco",
    "Guacamayo",
    "Guajolote",
    "Guepardo",
    "Halcón",
    "Hamster",
    "Hiena",
    "Hipopótamo",
    "Hormiga",
    "Hurón",
    "Ibis",
    "Iguana",
    "Impala",
    "Jabalí",
    "Jaguar",
    "Jaguarundi",
    "Jerbo",
    "Jilguero",
    "Jiracó",
    "Kaká",
    "Kakapo",
    "Kanguro",
    "Kiwi",
    "Koala",
    "Koi",
    "Krill",
    "Langosta",
    "Langostino",
    "Lechuza",
    "Lemur",
    "León",
    "Leopardo",
    "Liebre",
    "Lince",
    "Lirón",
    "Llama",
    "Lobo",
    "Lobo marino",
    "Lombriz",
    "Loro",
    "Lince ibérico",
    "Luciérnaga",
    "Macaco",
    "Macho cabrío",
    "Manta",
    "Mantarraya",
    "Manatí",
    "Mandril",
    "Mangosta",
    "Mantis",
    "Mapache",
    "Marabú",
    "Mariposa",
    "Marmota",
    "Marsopa",
    "Marta",
    "Mastín",
    "Mechón",
    "Medusa",
    "Mofeta",
    "Mono",
    "Morsa",
    "Mosca",
    "Mosquito",
    "Mula",
    "Murciélago",
    "Narval",
    "Náyade",
    "Nutria",
    "Ñandú",
    "Ocelote",
    "Ogro",
    "Olingo",
    "Orangután",
    "Orca",
    "Oruga",
    "Oso",
    "Oso hormiguero",
    "Oso marino",
    "Oso panda",
    "Oso polar",
    "Ovni",
    "Paca",
    "Pájaro",
    "Paloma",
    "Pantera",
    "Papagayo",
    "Papión",
    "Pargo",
    "Pariente",
    "Pato",
    "Pavo",
    "Pavo real",
    "Pecarí",
    "Pelecan",
    "Pelícano",
    "Perezoso",
    "Perico",
    "Perro",
    "Petirrojo",
    "Pez",
    "Pingüino",
    "Piojo",
    "Pitón",
    "Platija",
    "Platypus",
    "Pollo",
    "Pólipo",
    "Poney",
    "Poto",
    "Puercoespín",
    "Puma",
    "Pulga",
    "Pulpo",
    "Quebrantahuesos",
    "Quetzal",
    "Quirquincho",
    "Rana",
    "Rata",
    "Ratón",
    "Ratón marsupial",
    "Raya",
    "Reno",
    "Rinoceronte",
    "Rinoceronte blanco",
    "Rinoceronte negro",
    "Robalo",
    "Rorcual",
    "Rubor",
    "Ruiseñor",
    "Salamandra",
    "Salmonete",
    "Salmón",
    "Saltamontes",
    "Sangría",
    "Sapo",
    "Sardina",
    "Sepia",
    "Serpiente",
    "Serval",
    "Siamang",
    "Sisonte",
    "Solenodonte",
    "Soma",
    "Soricido",
    "Sotalia",
    "Sueño",
    "Suricata",
    "Tábano",
    "Tahr",
    "Taipán",
    "Takin",
    "Tamarino",
    "Tangara",
    "Tapir",
    "Tarántula",
    "Tarsero",
    "Tejón",
    "Tenedor",
    "Teniasis",
    "Tenrec",
    "Ternero",
    "Tiburón",
    "Tigre",
    "Tilacino",
    "Tití",
    "Topo",
    "Toro",
    "Tortuga",
    "Tritón",
    "Trucha",
    "Tucán",
    "Tule",
    "Tuátara",
    "Ualabí",
    "Uapití",
    "Ubre",
    "Urogallo",
    "Urraca",
    "Vaca",
    "Vampiro",
    "Vaquita",
    "Venado",
    "Víbora",
    "Visón",
    "Vitela",
    "Vivora",
    "Vizcacha",
    "Wapití",
    "Wallaby",
    "Wombat",
    "Xenopus",
    "Yacaré",
    "Yaguareté",
    "Yak",
    "Yam",
    "Zama",
    "Zancudo",
    "Zebra",
    "Zorro",
    "Zorro volador",
    "Zorzal",
    # ── Invertebrados extra ──
    "Abeja",
    "Alacrán",
    "Anémona",
    "Avispa",
    "Babosa",
    "Barbo",
    "Bicho de luz",
    "Calamar",
    "Cangrejo ermitaño",
    "Ciempiés",
    "Cochinilla de humedad",
    "Erizo de mar",
    "Estrella de mar",
    "Gusano",
    "Hydra",
    "Jabali",
    "Lamprea",
    "Langosta de mar",
    "Lapa",
    "Lombriz de tierra",
    "Mejillón",
    "Molusco",
    "Nautilo",
    "Nemátodo",
    "Ofiura",
    "Ostra",
    "Percebe",
    "Planaria",
    "Pulga de agua",
    "Sanguijuela",
    "Tenia",
    "Termita",
    "Triquina",
    "Vaquita de San Antonio",
    "Víbora de cascabel",
    # ── Aves extra ──
    "Alondra",
    "Avutarda",
    "Búho",
    "Cárabo",
    "Cardenal",
    "Cascanueces",
    "Cerceta",
    "Cigüeña",
    "Codorniz",
    "Cotorra",
    "Cuclillo",
    "Cuitlacoche",
    "Estornino",
    "Flamenco",
    "Gallareta",
    "Gallina",
    "Ganso",
    "Garza",
    "Grulla",
    "Halcón peregrino",
    "Jilguero",
    "Loro barranquero",
    "Martín pescador",
    "Mirlo",
    "Pato criollo",
    "Perdiz",
    "Pinzón",
    "Piranga",
    "Quelea",
    "Sinsonte",
    "Tordo",
    "Tucán",
    "Urraca",
    "Vencejo",
    "Zopilote",
    # ── Peces extra ──
    "Anguila",
    "Atún",
    "Bagre",
    "Bacalao",
    "Carpa",
    "Caviar",
    "Dorado",
    "Esturión",
    "Jurel",
    "Lenguado",
    "Lubina",
    "Merluza",
    "Mero",
    "Pez espada",
    "Pez globo",
    "Pez león",
    "Pez payaso",
    "Piraña",
    "Róbalo",
    "Sábalo",
    "Sierra",
    "Tilapia",
    "Trucha arcoíris",
]

THINGS: list[str] = [
    "Mesa",
    "Silla",
    "Cama",
    "Coche",
    "Casa",
    "Libro",
    "Lapiz",
    "Computadora",
    "Telefono",
    "Reloj",
    "Zapato",
    "Camisa",
    "Plato",
    "Vaso",
    "Llave",
    "Bolsa",
    "Ventana",
    "Puerta",
    "Lampara",
    "Cuchara",
    "Tenedor",
    "Cuchillo",
    "Television",
    "Radio",
    "Bicicleta",
    "Moto",
    "Avion",
    "Barco",
    "Tren",
    "Pelota",
    "Guitarra",
    "Piano",
    "Bateria",
    "Sofa",
    "Armario",
    "Estante",
    "Cuadro",
    "Espejo",
    "Almohada",
    "Sabana",
    "Cobija",
    "Colcha",
    "Toalla",
    "Jabon",
    "Champu",
    "Pasta dental",
    "Cepillo",
    "Pena",
    "Cortauñas",
    "Tijeras",
    "Regla",
    "Borrador",
    "Sacapuntas",
    "Mochila",
    "Maleta",
    "Cartera",
    "Monedero",
    "Boligrafo",
    "Marcador",
    "Resaltador",
    "Cuaderno",
    "Hoja",
    "Carpeta",
    "Escritorio",
    "Biblioteca",
    "Librero",
    "Cajon",
    "Gaveta",
    "Nevera",
    "Refrigerador",
    "Congelador",
    "Horno",
    "Microondas",
    "Lavadora",
    "Secadora",
    "Lavavajillas",
    "Aspiradora",
    "Plancha",
    "Tostadora",
    "Batidora",
    "Licuadora",
    "Cafetera",
    "Hervidor",
    "Olla",
    "Sarten",
    "Cazo",
    "Colador",
    "Rallador",
    "Pelador",
    "Tabla",
    "Rodillo",
    "Moldes",
    "Bandeja",
    "Charola",
    "Taza",
    "Vaso",
    "Jarra",
    "Botella",
    "Termo",
    "Cantimplora",
    "Servilleta",
    "Mantel",
    "Delantal",
    "Guantes",
    "Gorro",
    "Camisa",
    "Camiseta",
    "Pantalon",
    "Short",
    "Falda",
    "Vestido",
    "Chaqueta",
    "Abrigo",
    "Sueter",
    "Bufanda",
    "Gorra",
    "Sombrero",
    "Corbata",
    "Cinturon",
    "Calcetines",
    "Medias",
    "Zapatos",
    "Botas",
    "Sandalias",
    "Chanclas",
    "Tenis",
    "Zapatillas",
    "Paraguas",
    "Impermeable",
    "Gabardina",
    "Chaleco",
    "Anillo",
    "Collar",
    "Pulsera",
    "Aretes",
    "Reloj",
    "Gafas",
    "Lentes",
    "Cartera",
    "Bolso",
    "Mochila",
    "Llavero",
    "Candado",
    "Cadena",
    "Alambre",
    "Cuerda",
    "Soga",
    "Lazo",
    "Cinta",
    "Pegamento",
    "Tijeras",
    "Martillo",
    "Destornillador",
    "Llave inglesa",
    "Alicates",
    "Sierra",
    "Taladro",
    "Nivel",
    "Metro",
    "Cinta metrica",
    "Pala",
    "Pico",
    "Azada",
    "Rastrillo",
    "Manguera",
    "Regadera",
    "Maceta",
    "Tiesto",
    "Mesa",
    "Silla",
    "Banco",
    "Taburete",
    "Butaca",
    "Sillon",
    "Mecedora",
    "Hamaca",
    "Columpio",
    "Tobogan",
    "Subibaja",
    "Arena",
    "Pelota",
    "Cometa",
    "Papalote",
    "Yo-yo",
    "Trompo",
    "Canica",
    "Muneca",
    "Carro",
    "Bloques",
    "Rompecabezas",
    "Legos",
    "Consola",
    "Videojuego",
    "Control",
    "Volante",
    "Audifonos",
    "Bocina",
    "Parlante",
    "Microfono",
    "Camara",
    "Proyector",
    "Pantalla",
    "Monitor",
    "Teclado",
    "Raton",
    "USB",
    "Disco duro",
    "Memoria",
    "Bateria",
    "Cargador",
    "Cable",
    "Adaptador",
    "Router",
    "Modem",
    "Antena",
    "Satelite",
    "Bicicleta",
    "Triciclo",
    "Monopatín",
    "Patineta",
    "Patines",
    "Casco",
    "Rodilleras",
    "Coderas",
    "Chaleco salvavidas",
    "Linterna",
    "Foco",
    "Bombilla",
    "Veladora",
    "Vela",
    "Cerillo",
    "Fosforo",
    "Encendedor",
    "Mechero",
    "Cenicero",
    "Reloj de pared",
    "Despertador",
    "Reloj de pulso",
    "Cronometro",
    "Termometro",
    "Barometro",
    "Higrometro",
    "Pluviometro",
    "Calendario",
    "Agenda",
    "Diario",
    "Anuario",
    "Album",
    "Marco",
    "Portarretrato",
    "Album de fotos",
    "Caja",
    "Cofre",
    "Baul",
    "Arcon",
    "Cesta",
    "Canasta",
    "Bolsa",
    "Mochila",
    "Morral",
    "Zurron",
    "Alforja",
    "Cantimplora",
    "Brujula",
    "Mapa",
    "GPS",
    "Senial",
    "Bandera",
    "Pancarta",
    "Cartel",
    "Letrero",
    "Rotulo",
    "Anuncio",
    "Pizarron",
    "Pantalla",
    "Proyector",
    "Puntero",
    "Tiza",
    "Gis",
    "Mimeografo",
    "Fotocopiadora",
    "Impresora",
    "Scanner",
    "Fax",
    "Telefono",
    "Intercomunicador",
    "Citofono",
    "Timbre",
    "Bocina",
    "Altavoz",
    "Megafono",
    "Silbato",
    "Campana",
    "Trompeta",
    "Clarinete",
    "Saxofon",
    "Flauta",
    "Violin",
    "Chelo",
    "Contrabajo",
    "Arpa",
    "Guitarra",
    "Ukelele",
    "Bajo",
    "Banjo",
    "Mandolina",
    "Acordeon",
    "Armonica",
    "Tambor",
    "Bongo",
    "Conga",
    "Timbal",
    "Marimba",
    "Xilofono",
    "Campana",
    "Triangulo",
    "Pandereta",
    "Maraca",
    "Claves",
    "Gueiro",
    "Cascabel",
    "Sonaja",
    "Matraca",
    "Plato",
    "Cuenco",
    "Bol",
    "Tazon",
    "Taza",
    "Jarra",
    "Pichel",
    "Cantarito",
    "Tinaja",
    "Anfora",
    "Copa",
    "Florero",
    "Jarron",
    "Vaso",
    "Botella",
    "Frasco",
    "Tarro",
    "Lata",
    "Bidon",
    "Garrafa",
    "Cubo",
    "Balde",
    "Tina",
    "Lavabo",
    "Lavadero",
    "Fregadero",
    "Lavaplatos",
    "Lavamanos",
    "Inodoro",
    "Retrete",
    "Banera",
    "Ducha",
    "Regadera",
    "Llave",
    "Grifo",
    "Canilla",
    "Tuberia",
    "Cano",
    "Manguera",
    "Cisterna",
    "Tanque",
    "Deposito",
    "Alberca",
    "Pileta",
    "Estanque",
]

WORD_LIST_DATA_FULL: dict[str, list[str]] = {
    "color": [],  # ya existe en word_list_data.py, se deja vacio
    "fruta": [],  # ya existe en word_list_data.py, se deja vacio
    "pais": [],  # ya existe en word_list_data.py, se deja vacio
    "nombre": NAMES,
    "apellido": SURNAMES,
    "artista": ARTISTS,
    "animal": ANIMALS,
    "cosa": THINGS,
}
