"""
Listas completas de palabras para validacion en Stop Bot.
Cada entrada es el nombre tal como se escribe (con tildes, mayusculas, etc.),
el sistema normalizara al insertar a la BD.

Organizacion:
 - color: Lista plana de aprox 100 colores con variantes ES/LATAM.
 - fruta: lista plana de aprox 90 frutas con variantes ES/LATAM
 - pais: lista plana de aprox 200 paises + variantes ortograficas
"""

COLORS: list[str] = [
    # --- Basicos ---
    "Blanco",
    "Negro",
    "Gris",
    "Rojo",
    "Azul",
    "Amarillo",
    "Verde",
    "Naranja",
    "Anaranjado",
    "Morado",
    "Púrpura",
    "Violeta",
    "Rosa",
    "Rosado",
    "Marrón",
    "Café",
    # ── Cálidos ──
    "Carmesí",
    "Carmín",
    "Escarlata",
    "Bermellón",
    "Granate",
    "Vino",
    "Burdeos",
    "Coral",
    "Salmón",
    "Terracota",
    "Ladrillo",
    "Cobre",
    "Caoba",
    "Óxido",
    "Melocotón",
    "Durazno",
    "Albaricoque",
    "Ámbar",
    "Mostaza",
    "Dorado",
    "Oro",
    "Ocre",
    "Arena",
    "Beige",
    "Crema",
    "Marfil",
    "Hueso",
    # ── Azules ──
    "Celeste",
    "Turquesa",
    "Aguamarina",
    "Cian",
    "Índigo",
    "Añil",
    "Cerúleo",
    "Cobalto",
    "Ultramar",
    "Zafiro",
    # ── Verdes ──
    "Lima",
    "Oliva",
    "Esmeralda",
    "Jade",
    "Menta",
    "Musgo",
    "Pino",
    "Pistacho",
    "Caqui",
    # ── Amarillos ──
    "Canario",
    "Pastel",
    # ── Violetas y rosas ──
    "Lila",
    "Lavanda",
    "Malva",
    "Magenta",
    "Fucsia",
    "Orquídea",
    # ── Marrones ──
    "Chocolate",
    "Canela",
    "Avellana",
    "Castaño",
    "Tabaco",
    "Siena",
    "Tierra",
    "Habano",
    # ── Metálicos ──
    "Plata",
    "Plateado",
    "Bronce",
    "Latón",
    "Platino",
    "Titanio",
    # ── Especiales ──
    "Rubí",
    "Perla",
    "Nácar",
    "Ébano",
    "Humo",
    "Carbón",
    "Grafito",
    "Neón",
    "Fluorescente",
]

FRUITS: list[str] = [
    # A
    "Abiu",
    "Abiú",
    "Aceituna",
    "Acerola",
    "Aguacate",
    "Palta",
    "Akebia",
    "Albaricoque",
    "Damasco",
    "Chabacano",
    "Almendra",
    "Ananá",
    "Piña",
    "Arándano",
    "Arándano rojo",
    "Atemoya",
    "Avellana",
    "Açaí",
    # B
    "Babaco",
    "Badea",
    "Banana",
    "Plátano",
    "Banano",
    "Guineo",
    "Cambur",
    "Bergamota",
    "Borojó",
    # C
    "Cacao",
    "Caimito",
    "Carambola",
    "Cereza",
    "Guinda",
    "Chirimoya",
    "Ciruela",
    "Ciruela pasa",
    "Coco",
    # D
    "Dátil",
    "Durián",
    # E
    "Endrina",
    "Escaramujo",
    # F
    "Feijoa",
    "Frambuesa",
    "Fresa",
    "Frutilla",
    # G
    "Granada",
    "Granadilla",
    "Grosella",
    "Guanábana",
    "Guaraná",
    "Guayaba",
    # H
    "Higo",
    # I
    "Icaco",
    "Ilama",
    # J
    "Jaboticaba",
    "Jambo",
    "Jujuba",
    "Azufaifa",
    # K
    "Kaki",
    "Caqui",
    "Kiwi",
    "Kumquat",
    "Quinoto",
    # L
    "Limón",
    "Lima",
    "Lichi",
    "Longan",
    "Lúcuma",
    "Lulo",
    "Naranjilla",
    # M
    "Mamey",
    "Mamoncillo",
    "Quenepa",
    "Limoncillo",
    "Mandarina",
    "Mango",
    "Mangostán",
    "Manzana",
    "Maracuyá",
    "Parcha",
    "Fruta de la pasión",
    "Melocotón",
    "Melón",
    "Membrillo",
    "Mirabel",
    "Mora",
    "Zarzamora",
    # N
    "Naranja",
    "Naranja sanguina",
    "Naranja roja",
    "Nectarina",
    "Níspero",
    "Noni",
    # P
    "Papaya",
    "Lechosa",
    "Pera",
    "Persimón",
    "Physalis",
    "Uchuva",
    "Aguaymanto",
    "Pitanga",
    "Pitahaya",
    "Fruta del dragón",
    "Pomelo",
    "Toronja",
    # R
    "Rambután",
    # S
    "Sandía",
    "Patilla",
    "Sapote",
    "Zapote",
    # T
    "Tamarillo",
    "Tomate de árbol",
    "Tamarindo",
    "Tuna",
    "Higo chumbo",
    # U
    "Uva",
    "Uva espina",
    # Y
    "Yaca",
    "Jackfruit",
    "Yuzu",
    # Z
    "Zarzamora",
    # Las frutas duplicadas con nombres diferentes ya están incluidas arriba
    # con sus variantes (ej: "Palta" y "Aguacate")
    # ── Adiciones extra ──
    "Araza",
    "Bacoba",
    "Bacuri",
    "Biriba",
    "Cabeluda",
    "Caimarron",
    "Camu camu",
    "Canistel",
    "Capulin",
    "Caranda",
    "Ciruela criolla",
    "Ciruela de huesito",
    "Coco de agua",
    "Coco pelado",
    "Copoazu",
    "Corozo",
    "Cupuacu",
    "Damasco chileno",
    "Duraznillo",
    "Fruta del milagro",
    "Fruta milagrosa",
    "Granadilla",
    "Granadilla real",
    "Grosella espinosa",
    "Guabiroba",
    "Guama",
    "Guapururu",
    "Guaviyu",
    "Guayaba fresa",
    "Guayaba pera",
    "Higos chumbos",
    "Huito",
    "Inga",
    "Jabuticaba",
    "Jenipapo",
    "Jocote",
    "Jocote marron",
    "Jujuba",
    "Kino",
    "Kiwi dorado",
    "Kiwi verde",
    "Kumquat",
    "Lacuma",
    "Lima dulce",
    "Lima persa",
    "Limon mandarina",
    "Limon suizo",
    "Lucuma",
    "Maca",
    "Mamon",
    "Mamoncillo chino",
    "Mandarina clementina",
    "Mandarina reina",
    "Mango ataulfo",
    "Mango haden",
    "Mango kent",
    "Mango tommy",
    "Mangostino",
    "Manzana asada",
    "Manzana verde",
    "Maracuya",
    "Maracuya dulce",
    "Maracuya gigante",
    "Marañon",
    "Marmolada",
    "Melon cantalupo",
    "Melon galia",
    "Melon honeydew",
    "Membrillo japones",
    "Mora azul",
    "Mora frambuesa",
    "Mora negra",
    "Moriche",
    "Muruici",
    "Nance",
    "Naranja agria",
    "Naranja dulce",
    "Naranja mandarina",
    "Naranja valencia",
    "Naranjilla",
    "Nispero de Japon",
    "Noni",
    "Okra",
    "Oliva negra",
    "Oliva verde",
    "Pajuila",
    "Palma datilera",
    "Papaya hawaiana",
    "Papaya maradol",
    "Papaya mexicana",
    "Paraguayo",
    "Pata de vaca",
    "Paujil",
    "Pepino",
    "Pepino melon",
    "Pequi",
    "Perita",
    "Pitaia",
    "Pitanga",
    "Platano burro",
    "Platano macho",
    "Platano manzano",
    "Platano morado",
    "Pomarrosa",
    "Pomelo chino",
    "Pomelo rosado",
    "Pomelo blanco",
    "Pora",
    "Pulasan",
    "Quinoto",
    "Rabo de gato",
    "Rambutan",
    "Sandia amarilla",
    "Sandia sin semilla",
    "Sapodilla",
    "Saramuyo",
    "Seriguela",
    "Sorva",
    "Soursop",
    "Tamarindo dulce",
    "Tangerina",
    "Taro",
    "Tasajo",
    "Tejocote",
    "Tomate de arbol",
    "Tuna blanca",
    "Tuna roja",
    "Uchuva",
    "Uva pasa",
    "Uva moscatel",
    "Uva verde",
    "Uvilla",
    "Vitamina",
    "Xigua",
    "Zapote blanco",
    "Zapote mamey",
    "Zapote negro",
    "Zarzamora azul",
    "Zarzamora roja",
    "Zarzaparrilla",
]

COUNTRIES: list[str] = [
    "Afganistán",
    "Albania",
    "Alemania",
    "Andorra",
    "Angola",
    "Antigua y Barbuda",
    "Arabia Saudita",
    "Argelia",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaiyán",
    # B
    "Bahamas",
    "Baréin",
    "Bangladés",
    "Barbados",
    "Bélgica",
    "Belice",
    "Benín",
    "Bielorrusia",
    "Birmania",
    "Myanmar",
    "Bolivia",
    "Bosnia y Herzegovina",
    "Botsuana",
    "Brasil",
    "Brunéi",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Bután",
    # C
    "Cabo Verde",
    "Camboya",
    "Camerún",
    "Canadá",
    "Catar",
    "Qatar",
    "Chad",
    "Chile",
    "China",
    "Chipre",
    "Ciudad del Vaticano",
    "Vaticano",
    "Colombia",
    "Comoras",
    "Corea del Norte",
    "Corea del Sur",
    "Costa de Marfil",
    "Costa Rica",
    "Croacia",
    "Cuba",
    # D
    "Dinamarca",
    "Dominica",
    # E
    "Ecuador",
    "Egipto",
    "El Salvador",
    "Emiratos Árabes Unidos",
    "Eritrea",
    "Eslovaquia",
    "Eslovenia",
    "España",
    "Estados Unidos",
    "Estado de Palestina",
    "Palestina",
    "Estonia",
    "Esuatini",
    "Etiopía",
    # F
    "Filipinas",
    "Finlandia",
    "Fiyi",
    "Francia",
    # G
    "Gabón",
    "Gambia",
    "Georgia",
    "Ghana",
    "Granada",
    "Grecia",
    "Guatemala",
    "Guinea",
    "Guinea-Bisáu",
    "Guinea Ecuatorial",
    "Guyana",
    # H
    "Haití",
    "Honduras",
    "Hungría",
    # I
    "India",
    "Indonesia",
    "Irak",
    "Irán",
    "Irlanda",
    "Islandia",
    "Islas Marshall",
    "Islas Salomón",
    "Israel",
    "Italia",
    # J
    "Jamaica",
    "Japón",
    "Jordania",
    # K
    "Kazajistán",
    "Kenia",
    "Kirguistán",
    "Kiribati",
    "Kuwait",
    # L
    "Laos",
    "Lesoto",
    "Letonia",
    "Líbano",
    "Liberia",
    "Libia",
    "Liechtenstein",
    "Lituania",
    "Luxemburgo",
    # M
    "Macedonia del Norte",
    "Madagascar",
    "Malasia",
    "Malaui",
    "Maldivas",
    "Malí",
    "Malta",
    "Marruecos",
    "Mauricio",
    "Mauritania",
    "México",
    "Micronesia",
    "Moldavia",
    "Moldova",
    "Mónaco",
    "Mongolia",
    "Montenegro",
    "Mozambique",
    # N
    "Namibia",
    "Nauru",
    "Nepal",
    "Nicaragua",
    "Níger",
    "Nigeria",
    "Noruega",
    "Nueva Zelanda",
    # O
    "Omán",
    # P
    "Países Bajos",
    "Pakistán",
    "Palaos",
    "Panamá",
    "Papúa Nueva Guinea",
    "Paraguay",
    "Perú",
    "Polonia",
    "Portugal",
    # R
    "Reino Unido",
    "República Centroafricana",
    "República Checa",
    "Chequia",
    "República del Congo",
    "República Democrática del Congo",
    "República Dominicana",
    "Ruanda",
    "Rumanía",
    "Rusia",
    # S
    "Samoa",
    "San Cristóbal y Nieves",
    "San Marino",
    "San Vicente y las Granadinas",
    "Santa Lucía",
    "Santo Tomé y Príncipe",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leona",
    "Singapur",
    "Siria",
    "Somalia",
    "Sri Lanka",
    "Sudáfrica",
    "Sudán",
    "Sudán del Sur",
    "Suecia",
    "Suiza",
    "Surinam",
    # T
    "Tailandia",
    "Tanzania",
    "Tayikistán",
    "Timor Oriental",
    "Togo",
    "Tonga",
    "Trinidad y Tobago",
    "Túnez",
    "Turkmenistán",
    "Turquía",
    "Türkiye",
    "Tuvalu",
    # U
    "Ucrania",
    "Uganda",
    "Uruguay",
    "Uzbekistán",
    # V
    "Vanuatu",
    "Venezuela",
    "Vietnam",
    # Y
    "Yemen",
    "Yibuti",
    # Z
    "Zambia",
    "Zimbabue",
]

# --- Mapa de categorias para el seed ---

WORD_LIST_DATA: dict[str, list[str]] = {
    "color": COLORS,
    "fruta": FRUITS,
    "pais": COUNTRIES,
}
