"""delete unique=true from name in seasonal_events

Revision ID: 15998b31dd96
Revises: cc4baf03d26f
Create Date: 2026-07-22 09:58:17.926969
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15998b31dd96'
down_revision: Union[str, None] = 'cc4baf03d26f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('seasonal_events_name_key'), 'seasonal_events', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('seasonal_events_name_key'), 'seasonal_events', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###