"""add_event_type_rules_daily_schedule_is_paused

Revision ID: 1c78ba01576f
Revises: 15998b31dd96
Create Date: 2026-07-22 11:29:05.695287
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c78ba01576f'
down_revision: Union[str, None] = '15998b31dd96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Hacer starts_at y ends_at nullable (antes eran NOT NULL)
    op.alter_column('seasonal_events', 'starts_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('seasonal_events', 'ends_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # Agregar columnas nuevas
    # event_type, timezone, is_paused: NOT NULL con server_default para datos existentes
    op.add_column('seasonal_events', sa.Column('event_type', sa.String(length=20), server_default='one_time', nullable=False))
    op.add_column('seasonal_events', sa.Column('daily_start_hour', sa.Integer(), nullable=True))
    op.add_column('seasonal_events', sa.Column('daily_start_minute', sa.Integer(), nullable=True))
    op.add_column('seasonal_events', sa.Column('daily_end_hour', sa.Integer(), nullable=True))
    op.add_column('seasonal_events', sa.Column('daily_end_minute', sa.Integer(), nullable=True))
    op.add_column('seasonal_events', sa.Column('active_days', sa.Text(), nullable=True))
    op.add_column('seasonal_events', sa.Column('timezone', sa.String(length=40), server_default='America/Argentina/Buenos_Aires', nullable=False))
    op.add_column('seasonal_events', sa.Column('rules', sa.Text(), nullable=True))
    op.add_column('seasonal_events', sa.Column('is_paused', sa.Boolean(), server_default='false', nullable=False))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seasonal_events', 'ends_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('seasonal_events', 'starts_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('seasonal_events', 'is_paused')
    op.drop_column('seasonal_events', 'rules')
    op.drop_column('seasonal_events', 'timezone')
    op.drop_column('seasonal_events', 'active_days')
    op.drop_column('seasonal_events', 'daily_end_minute')
    op.drop_column('seasonal_events', 'daily_end_hour')
    op.drop_column('seasonal_events', 'daily_start_minute')
    op.drop_column('seasonal_events', 'daily_start_hour')
    op.drop_column('seasonal_events', 'event_type')
    # ### end Alembic commands ###