"""add_word_list_items

Revision ID: 42c65e17a6d6
Revises: 0001
Create Date: 2026-07-03 14:13:10.749508
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "42c65e17a6d6"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "word_list_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("word", sa.String(length=128), nullable=False),
        sa.Column("normalized", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_word_list_items_category"), "word_list_items", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_word_list_items_normalized"), "word_list_items", ["normalized"], unique=False
    )
    op.create_index(op.f("ix_answers_player_id"), "answers", ["player_id"], unique=False)
    op.create_index(op.f("ix_answers_round_id"), "answers", ["round_id"], unique=False)
    op.drop_constraint(op.f("group_configs_group_chat_id_key"), "group_configs", type_="unique")
    op.drop_index(op.f("ix_group_configs_group_chat_id"), table_name="group_configs")
    op.create_index(
        op.f("ix_group_configs_group_chat_id"), "group_configs", ["group_chat_id"], unique=True
    )
    op.drop_constraint(op.f("players_telegram_id_key"), "players", type_="unique")
    op.drop_index(op.f("ix_players_telegram_id"), table_name="players")
    op.create_index(op.f("ix_players_telegram_id"), "players", ["telegram_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_players_telegram_id"), table_name="players")
    op.create_index(op.f("ix_players_telegram_id"), "players", ["telegram_id"], unique=False)
    op.create_unique_constraint(
        op.f("players_telegram_id_key"),
        "players",
        ["telegram_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_group_configs_group_chat_id"), table_name="group_configs")
    op.create_index(
        op.f("ix_group_configs_group_chat_id"), "group_configs", ["group_chat_id"], unique=False
    )
    op.create_unique_constraint(
        op.f("group_configs_group_chat_id_key"),
        "group_configs",
        ["group_chat_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_answers_round_id"), table_name="answers")
    op.drop_index(op.f("ix_answers_player_id"), table_name="answers")
    op.drop_index(op.f("ix_word_list_items_normalized"), table_name="word_list_items")
    op.drop_index(op.f("ix_word_list_items_category"), table_name="word_list_items")
    op.drop_table("word_list_items")
    # ### end Alembic commands ###
