"""add_message_logs

Revision ID: 44434a41785d
Revises: 864f644481b0
Create Date: 2026-07-07 12:28:39.558611
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "44434a41785d"
down_revision: str | None = "864f644481b0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_message_logs_chat_id"), "message_logs", ["chat_id"], unique=False)
    op.drop_constraint(op.f("answers_player_id_fkey"), "answers", type_="foreignkey")
    op.drop_constraint(op.f("answers_game_player_id_fkey"), "answers", type_="foreignkey")
    op.drop_constraint(op.f("answers_round_id_fkey"), "answers", type_="foreignkey")
    op.create_foreign_key(
        None, "answers", "game_players", ["game_player_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(None, "answers", "rounds", ["round_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(None, "answers", "players", ["player_id"], ["id"], ondelete="CASCADE")
    op.create_unique_constraint("uq_game_player", "game_players", ["game_id", "player_id"])
    op.drop_constraint(op.f("game_players_player_id_fkey"), "game_players", type_="foreignkey")
    op.drop_constraint(op.f("game_players_game_id_fkey"), "game_players", type_="foreignkey")
    op.create_foreign_key(
        None, "game_players", "players", ["player_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(None, "game_players", "games", ["game_id"], ["id"], ondelete="CASCADE")
    op.create_index(op.f("ix_rounds_game_id"), "rounds", ["game_id"], unique=False)
    op.drop_constraint(op.f("rounds_stopped_by_player_id_fkey"), "rounds", type_="foreignkey")
    op.drop_constraint(op.f("rounds_game_id_fkey"), "rounds", type_="foreignkey")
    op.create_foreign_key(None, "rounds", "games", ["game_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(
        None, "rounds", "players", ["stopped_by_player_id"], ["id"], ondelete="SET NULL"
    )
    op.create_unique_constraint(
        "uq_player_week", "weekly_leaderboards", ["player_id", "week_start"]
    )
    op.drop_constraint(
        op.f("weekly_leaderboards_player_id_fkey"), "weekly_leaderboards", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "weekly_leaderboards", "players", ["player_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_index(op.f("ix_word_list_items_source"), table_name="word_list_items")
    op.create_unique_constraint("uq_category_word", "word_list_items", ["category", "normalized"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_category_word", "word_list_items", type_="unique")
    op.create_index(op.f("ix_word_list_items_source"), "word_list_items", ["source"], unique=False)
    op.drop_constraint(None, "weekly_leaderboards", type_="foreignkey")
    op.create_foreign_key(
        op.f("weekly_leaderboards_player_id_fkey"),
        "weekly_leaderboards",
        "players",
        ["player_id"],
        ["id"],
    )
    op.drop_constraint("uq_player_week", "weekly_leaderboards", type_="unique")
    op.drop_constraint(None, "rounds", type_="foreignkey")
    op.drop_constraint(None, "rounds", type_="foreignkey")
    op.create_foreign_key(op.f("rounds_game_id_fkey"), "rounds", "games", ["game_id"], ["id"])
    op.create_foreign_key(
        op.f("rounds_stopped_by_player_id_fkey"),
        "rounds",
        "players",
        ["stopped_by_player_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_rounds_game_id"), table_name="rounds")
    op.drop_constraint(None, "game_players", type_="foreignkey")
    op.drop_constraint(None, "game_players", type_="foreignkey")
    op.create_foreign_key(
        op.f("game_players_game_id_fkey"), "game_players", "games", ["game_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("game_players_player_id_fkey"), "game_players", "players", ["player_id"], ["id"]
    )
    op.drop_constraint("uq_game_player", "game_players", type_="unique")
    op.drop_constraint(None, "answers", type_="foreignkey")
    op.drop_constraint(None, "answers", type_="foreignkey")
    op.drop_constraint(None, "answers", type_="foreignkey")
    op.create_foreign_key(op.f("answers_round_id_fkey"), "answers", "rounds", ["round_id"], ["id"])
    op.create_foreign_key(
        op.f("answers_game_player_id_fkey"), "answers", "game_players", ["game_player_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("answers_player_id_fkey"), "answers", "players", ["player_id"], ["id"]
    )
    op.drop_index(op.f("ix_message_logs_chat_id"), table_name="message_logs")
    op.drop_table("message_logs")
    # ### end Alembic commands ###
