"""add group_chat_id to seasonal_events

Revision ID: cc4baf03d26f
Revises: ef3389d3a2c2
Create Date: 2026-07-22 09:57:15.046974
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc4baf03d26f'
down_revision: Union[str, None] = 'ef3389d3a2c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seasonal_events', sa.Column('group_chat_id', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_seasonal_events_group_chat_id'), 'seasonal_events', ['group_chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seasonal_events_group_chat_id'), table_name='seasonal_events')
    op.drop_column('seasonal_events', 'group_chat_id')
    # ### end Alembic commands ###