"""add bot_chats and group_chat_id to seasonal_events

Revision ID: ef3389d3a2c2
Revises: e1
Create Date: 2026-07-22 09:54:55.898926
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef3389d3a2c2'
down_revision: Union[str, None] = 'e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_title', sa.String(length=256), nullable=False),
    sa.Column('chat_type', sa.String(length=20), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_chats_chat_id'), 'bot_chats', ['chat_id'], unique=True)
    op.alter_column('game_state_cache', 'key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('game_state_cache', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_state_cache', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('game_state_cache', 'key',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_bot_chats_chat_id'), table_name='bot_chats')
    op.drop_table('bot_chats')
    # ### end Alembic commands ###